spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3316/webshop
    username: root
    password:
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update



## If default port already in use
server:
  port: 8085
  ## Session timeout
  servlet:
    session:
      timeout:
